/**
 * Passphrase wordlist.
 *
 * Curated for diceware-style passphrases: short, common, unambiguous English
 * words with no profanity, no offensive terms and no easily-confused
 * homophones. The list is deduplicated and frozen at module load, and the
 * entropy calculation always uses the *actual* runtime length, so the security
 * numbers shown in the UI stay honest if the list ever changes.
 */

const RAW = `
abacus able about above absorb abstract absurd accent accept access accord account ache acid acorn acre across act action active actor actual adapt add adept adjust admire admit adobe adopt adult advance advice affair afford afraid after again age agency agent agile agree ahead aim air aisle alarm album alert algae alien align alike alive alley allow almond almost aloft alone along aloud alpha also altar alter always amaze amber amble amend amid among amount ample amuse anchor ancient angel anger angle animal ankle annual answer antenna anthem antique anvil anxiety any apart apex apology appeal appear apple apply april apron arcade arch archer arctic area arena argue arise arm armor army aroma around array arrive arrow art artist ash aside ask aspect asset assist assume athlete atlas atom attach attack attend attic auction audio audit august aunt author auto autumn avatar avenue avoid awake award aware away awesome awful axis
baby back bacon badge bag bake balance balcony bald ball balloon bamboo banana band bandit bank banner banquet bar barbecue barge barn barrel base basic basil basin basket bat batch bath batter bay beach beacon bead beam bean bear beard beast beat beauty beaver become bed bee beef beetle before begin behave behind being belief bell belong below belt bench bend benefit bent berry beside best bet better between beyond bicycle bid big bike bill bin binary bind biology bird birth biscuit bishop bison bit bite bitter black blade blame blank blanket blast blaze bleach blend bless blind blink block blond blood bloom blossom blot blouse blow blue bluff blunt blur blush board boast boat body boil bold bolt bond bone bonus book boost boot border bore borrow boss both bottle bottom bounce bound bow bowl box boy brace bracket braid brain brake branch brand brass brave bread break breath breeze brick bride bridge brief bright brim bring brisk broad broken bronze brook broom brother brown brush bubble bucket buddy budget buffalo buffet bug build bulb bulk bull bumper bunch bundle bunk bunny burden burger burn burst bury bus bush busy butter button buy buzz
cabin cable cactus cage cake calm camel camera camp can canal cancel candle candy cane canoe canvas canyon cap cape captain car carbon card care cargo carpet carrot carry cart carve case cash casino cast castle casual cat catalog catch cattle cause caution cave cease cedar ceiling celery cell cement census cent center century ceramic cereal certain chain chair chalk champion chance change channel chaos chapter charge charity charm chart chase chat cheap check cheek cheer cheese chef cherry chess chest chew chicken chief child chill chimney chip chirp choice choir choose chop chorus chrome chunk church cider cigar cinema circle circuit citizen city civic civil claim clam clap clarify clash class classic claw clay clean clear clerk clever click client cliff climb clinic clip clock clone close cloth cloud clover clown club clue cluster clutch coach coal coast coat cobra cocoa code coffee coil coin cold collar collect colony color column comb combine come comfort comic command comment common compact company compare compass compete complex comply concert conduct cone confirm connect consider console constant contact contain content contest context control convert cook cool copper copy coral cord core cork corn corner correct cost cottage cotton couch cough could council count country couple courage course court cousin cover cow coyote cozy crab crack cradle craft crane crash crater crawl crazy cream create credit creek crew cricket crime crisp critic crop cross crowd crown crucial cruise crumb crunch crush crust cry crystal cube cuddle cue cuisine culture cup curb cure curious curl current curtain curve cushion custom cute cycle
dad daily dairy daisy damage damp dance danger dare dark dash data date dawn day dead deal dear debate debris decade decent decide deck declare decline decor decrease deep deer defend define degree delay delight deliver demand demo denim dense dental deny depart depend deposit depth deputy derby desert design desk detail detect develop device devote dial diamond diary dice diesel diet differ digital dignity dilemma dinner dinosaur direct dirt disagree discover dish disk dismiss display distance ditch dive divert divide dizzy doctor document dodge dog doll dolphin domain dome donate donkey donor door dose dot double dough dove down dozen draft dragon drain drama draw dream dress drift drill drink drive drop drum dry duck due dune during dusk dust duty dwarf dwell dynamic
eager eagle early earn earth ease east easy echo eclipse ecology edge edit educate effort egg eight either elbow elder electric elegant element elephant elevate elite else embark ember embrace emerge emotion employ empty enable enact enamel enclose encode end endless endorse endure enemy energy enforce engage engine enhance enjoy enlist enough enrich enroll ensure enter entire entry envelope envy epic episode equal equator equip era erase erode errand error erupt escape essay essence estate eternal ethics evening event ever every evidence evolve exact exam example exceed excess exchange excite exclude excuse exercise exhaust exhibit exile exist exit exotic expand expect expert expire explain export expose extend extra extreme eye
fabric face fact factor fade faint fair faith falcon fall false fame family famous fan fancy fantasy far farm fashion fast fat fatal father fatigue fault favor fear feast feather feature february fee feed feel fellow female fence fern ferry festival fetch fever few fiber fiction field fifteen fifth fifty fig fight figure file fill film filter final find fine finger finish fire firm first fiscal fish fist fit five fix flag flame flash flat flavor flee fleet flesh flex flight flip float flock flood floor flour flow flower fluid flush flute fly foam focus fog foil fold folk follow food foot force forest forget fork form fort forth fortune forum forward fossil foster found four fox fragile frame free freeze fresh friend fringe frog front frost frown frozen fruit fuel full fun funny furnace fury future
gadget gain galaxy gallery game gap garage garden garlic garment gas gasp gate gather gauge gaze gear general genius gentle genuine gesture ghost giant gift giggle ginger giraffe girl give glad glance glass glide glimpse globe gloom glory glove glow glue goal goat gold golf good goose gorilla gospel govern gown grab grace grade grain grand granite grant grape graph grasp grass gravel gravity gray great green greet grid grief grill grin grip grocery groove ground group grove grow guard guess guest guide guilt guitar gulf gum gust gym
habit hair half hall hammer hamster hand handle happy harbor hard hare harmony harsh harvest hat hatch have hawk hazard hazel head heal health heap hear heart heat heavy hedge height helmet help hen herb herd here hero hidden hide high hike hill hint hip hire history hobby hockey hold hole holiday hollow home honest honey honor hood hoof hook hope horn horse hospital host hotel hour house hover howl hub huge human humble humid humor hundred hunger hunt hurdle hurry hurt husband hybrid
ice icon idea ideal identify idle ignite ignore ill image imitate immense immune impact impose improve impulse inch include income increase indeed index indoor infant inflate inform inhale initial inject injury ink inland inmate inner input inquiry insane insect inside insight inspire install instant instead intact intend interest into invest invite involve iron island isolate issue item ivory
jacket jaguar jam january jar jaw jazz jealous jeans jelly jewel job jog join joke journal journey joy judge juice july jump june jungle junior junk just
kangaroo keen keep kernel ketchup kettle key kick kid kidney kind king kiosk kiss kit kitchen kite kitten kiwi knee knife knight knit knock knot know
lab label labor lace ladder lady lake lamp land lane language laptop large laser last late laugh launch laundry lava law lawn layer lazy lead leaf lean learn lease leash least leather leave lecture ledge left leg legal legend legume leisure lemon length lens leopard lesson letter level liar liberty library license lid life lift light like lilac lily limb lime limit line linen link lion liquid list listen little live lizard load loaf loan lobby local lock logic lonely long look loop loose lord lose lot loud lounge love loyal lucky luggage lumber lunar lunch lung luxury lyric
machine mad magic magnet maid mail main major make mammal man manage mango manner mansion manual maple marble march margin marine market marriage mask mason mass master match material math matrix matter maximum may maybe mayor maze meadow meal mean measure meat mechanic medal media medium meet melody melon melt member memory mention menu mercy merge merit merry mesh message metal method middle midnight might mild mile milk mill mimic mind mine minute miracle mirror miss mistake mix mobile model modern modest modify moment monitor monkey monster month mood moon moral more morning mosaic most mother motion motor mountain mouse mouth move movie much muffin mule multiply muscle museum mushroom music must mutual myself mystery myth
naive name napkin narrow nasty nation native nature navy near neat neck need needle negative neglect neighbor neon nephew nerve nest net network neutral never new news next nice niece night nine noble node noise nominal noodle noon normal north nose note notice novel november now nuclear number nurse nut
oak obey object oblige obscure observe obtain obvious occur ocean october odd odor offer office often oil okay old olive omit once one onion online only open opera opinion oppose option orange orbit orchard order ordinary organ origin orphan ostrich other otter ought ounce outdoor outer output outside oval oven over owl own oxygen oyster ozone
pace pack pact paddle page pair palace pale palm panda panel panic panther paper parade parent park parrot part party pass past pasta patch path patient patrol pattern pause pave payment peace peach peak peanut pear pearl peasant pebble pedal peel peer pelican pen penalty pencil people pepper perch perfect perform perhaps period permit person pet phone photo phrase physical piano pick picnic picture pie piece pig pigeon pile pilot pin pine pink pioneer pipe pistol pitch pizza place plain plan planet plank plant plastic plate play plaza pleasant please pledge plenty plot plug plum plunge pocket poem poet point polar pole police policy polish polite pond pony pool poor popular porch port portion portrait position possible post pot potato pottery pouch pound pour powder power praise pray predict prefer premium prepare present press pretty prevent price pride primary print prior prism prison private prize problem process produce profit program project promise proof proper protect proud prove provide public pudding puddle pull pulse pump punch pupil puppy purchase pure purple purpose purse push put puzzle pyramid
quality quantum quarter queen query quest question quick quiet quilt quit quiz quote
rabbit raccoon race rack radar radio radish raft rail rain raise rally ramp ranch random range rank rapid rare rate rather ratio raven raw ray razor reach read ready real reason rebel rebuild recall receive recipe record recover recycle red reduce reef refer reflect reform refuse region regret regular reject relax release relief rely remain remedy remember remind remote remove render renew rent repair repeat replace reply report request rescue research reserve resist resort resource respond rest result retail retire retreat return reunion reveal review reward rhythm ribbon rice rich ride ridge rifle right rigid ring rinse riot ripe rise risk ritual rival river road roast robot robust rock rocket rod role roll roof room root rope rose rotate rough round route routine royal rubber rude rug rule run runway rural rush
sad saddle safe sail salad salary salmon salon salt salute same sample sand satisfy sauce sausage save say scale scan scarf scatter scene schedule scheme scholar school science scissors scoop scope score scout scrap screen script scrub sculpt sea seal search season seat second secret section secure seed seek seem segment select self sell send senior sense sentence series serious serve service session settle seven several severe shadow shaft shallow shampoo shape share shark sharp shed sheep sheet shelf shell shelter shield shift shine ship shirt shiver shock shoe shoot shop shore short shoulder shove show shower shrimp shrink shrug shuffle shy sibling sick side siege sight sign silent silk silly silver similar simple since sing single sink sir sister sit site six size skate sketch ski skill skin skirt skull sky slab slam sleep sleeve slender slice slide slight slim slogan slope slot slow small smart smell smile smoke smooth snack snake snap sneak sniff snow soap social sock soda soft soil solar soldier solid solve some song soon sorry sort soul sound soup source south space spare spark speak special speed spell spend sphere spice spider spike spin spirit split spoil sponge spoon sport spot spray spread spring sprout spy square squash squeeze stable stack stadium staff stage stairs stamp stand star start state station stay steady steak steal steam steel steep stem step stereo stick still sting stir stock stomach stone stool stop store storm story stove strange straw stream street stress strike string strong struggle student studio study stuff style subject submit subway success such sudden suffer sugar suggest suit summer summit sun super supply support suppose sure surface surge surprise surround survey survive suspect sustain swallow swamp swan swap swarm sweat sweep sweet swell swift swim swing switch sword symbol symptom syrup system
table tackle tag tail talent talk tall tank tape target task taste tattoo taxi tea teach team tear tech teen tell temple ten tenant tennis tent term test text thank that theme then theory there they thick thin thing think third thirty this thorn those though thread three thrive throat throw thumb thunder ticket tide tidy tiger tight tile timber time tiny tip tired tissue title toast today toddler toe together toilet token tomato tomorrow tone tongue tonight tool tooth top topic torch total touch tough tour toward towel tower town toy track trade traffic trail train transfer trap trash travel tray treat tree trend trial tribe trick trigger trim trip trophy tropic trouble truck true trumpet trust truth try tube tuition tumble tuna tunnel turkey turn turtle twelve twenty twice twin twist two type typical
ugly umbrella unable uncle under undo unfair unfold unhappy uniform union unique unit universe unknown unlock until unusual unveil update upgrade uphold upon upper upset urban urge usage use useful usual utility
vacant vacuum vague valid valley value valve van vanish vapor variety various vast vault vector vehicle velvet vendor venture venue verb verdict verify verse version very vessel veteran viable vibrant vicious victory video view village vintage violet violin virtual virus visa visible vision visit visual vital vivid vocal voice void volcano volume vote voyage
wage wagon waist wait wake walk wall walnut want warm warn wash wasp waste watch water wave wax way wealth weapon wear weasel weather weave wedding weekend weight weird welcome west wet whale what wheat wheel when where which while whip whisper white whole wide width wife wild will win wind window wine wing wink winner winter wire wisdom wise wish witness wolf woman wonder wood wool word work world worry worth wrap wreck wrench wrist write wrong
yard yarn year yellow yes yet yield yoga yogurt young youth
zebra zero zone zoo
`;

export const WORDLIST: readonly string[] = Object.freeze([
  ...new Set(
    RAW.split(/\s+/)
      .map((w) => w.trim().toLowerCase())
      .filter((w) => /^[a-z]{2,9}$/.test(w)),
  ),
]);

export const WORDLIST_SIZE = WORDLIST.length;
